name: notes-backend

services:
  notes-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3001:80
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_USER}:${NOTES_PASSWORD}@notes-db/${NOTES_DB}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    networks:
      - notes-net
    depends_on:
      - notes-db
  notes-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: volume
        source: notes-vol
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    networks:
      - notes-net

volumes:
  notes-vol:

networks:
  notes-net:
